apiVersion: v1
kind: Service
metadata:
  name: go-date-time-service
spec:
  type: LoadBalancer
  selector:
    app: go-date-time-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000
